### ISSUE TITLE
Investigate VAD

### ISSUE THREAD

**Issue by Atmelfan** [gpa-fryk-industries/CDIO#12]
We should start to look into Voice Activity Detection (VAD) algorithms.

**Comment by davfr422** [comment]
http://iopscience.iop.org/article/10.1088/1742-6596/705/1/012037/pdf 
I will try this one and see where it leads.

**Comment by davfr422** [comment]
I think we should consider this if we have time. I was looking into some papers and it seems pretty complicated to do and especially complicated to implement on an FPGA.
