### ISSUE TITLE
ICE40UP5K Dev Kit.

### ISSUE THREAD

**Issue by davfr422** [gpa-fryk-industries/CDIO#15]
I'm thinking about buying one of these for testing the FPGA. I believe this is the best option Lattice offers. 
https://www.mouser.se/ProductDetail/Lattice/iCE40UP5K-B-EVN?qs=sGAEpiMZZMuYaq4aOfOV%252bHfKKD%2f%2fNImMyBkFo4nc5Ic%3d

**Comment by Atmelfan** [comment]
Sounds good for me. Tell Knutsson and then close the issue.

**Comment by davfr422** [comment]
Forgot about it today, I'll sent him an email with the product tomorrow. Closing issue when he has ordered it.

**Comment by Atmelfan** [comment]
Not related to PCB milestone.
