### ISSUE TITLE
Update rules for altium.

### ISSUE THREAD

**Issue by davfr422** [gpa-fryk-industries/CDIO#16]
Name power nets + add rules for minimun width for net class. 
Polygon rules to draw beautiful supply voltage rails. 
Clearance.
Any other suggestions? Not really an expert on this topic.

**Comment by Atmelfan** [comment]
I suggest these basic rules:
-1: clearance: all, all - 6mil
-2: clearance: inpolygon, all - 10mil
-3: board outline clearance: all - 20mil
-4: trace width: 6mil min, 8mil preferred, 100mil maximum

**Comment by davfr422** [comment]
Done and done.
