### ISSUE TITLE
Skype while Mr. GPA is in Mali.

### ISSUE THREAD

**Issue by davfr422** [gpa-fryk-industries/CDIO#18]
Skype 22:15 every day this week? Need to get in contact with you. Either that or activate facebook.

**Comment by Atmelfan** [comment]
No Facebook.

**Comment by Atmelfan** [comment]
22:15 och is 20:15 here. Will be hard but I'll try.

**Comment by davfr422** [comment]
What time suits you then?

**Comment by Atmelfan** [comment]
Fuck facebook
