### ISSUE TITLE
FPGA Signals

### ISSUE THREAD

**Issue by Atmelfan** [gpa-fryk-industries/CDIO#8]
What signals are required between MCU and FPGA? Currently only basic configuration signals are connected (can be used as SPI once configuration is done).

What other signal should be shared? 
Suggestions:

- [x]  Interrupt request (IRQ)
- [x]  Master/slave control to avoid FPGA/MCU collision in case the FPGA can act as master

More suggestions?

**Comment by davfr422** [comment]
There has to some kind of coherence for what's actually going on inside the FPGA during debugging. I guess SPI communication is an alright interface for sharing signals. Let's discuss this more in detail on monday. I feel like I need to better understand the issue in order to give a better answer.

**Comment by Atmelfan** [comment]
Added ATT (ATTention) and MINH (Master INHibit) signals between the FPGA and MCU.
